Adding GitHub Action (in progress) and two test cases in C
adityaxdiwakar/py-lexer pull request #2
Opened 2023-11-03 19:35 UTC by CC-734

the workflow is not totally working yet but runs when a file is pushed and will use diff to compare expected lex values to that of the output from lex.py

2023-11-03 20:45 UTC, adityaxdiwakar commented
Until your PR is ready, you can let this PR stay as a draft. I'll review in the meantime, though.

2023-11-03 20:46 UTC, adityaxdiwakar commented
What is not working?

2023-11-03 21:09 UTC, adityaxdiwakar requested changes
Mostly good, missing some things -- I tried to leave most things as suggestions so you should be able to instantly commit without editing the files. There are **22** changes I suggest.

Beyond that, please separate out the expected output like I said in @ritvik-knagaram's PR in #1 

Thank you!

We'll talk offline about the workflow not working.

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +STR
```suggestion
STR(stdio.h)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +LBRACK
```suggestion
IDENT(main)
LPAREN
RPAREN
LBRACK
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +INT_WORD
```suggestion
INT_WORD
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +IDENT(scanf)
```suggestion
SEMI
IDENT(scanf)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +IDENT(x)
```suggestion
COMMA
ANDREF
IDENT(x)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +IDENT(y)
```suggestion
COMMA
ANDREF
IDENT(y)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +LPAREN
```suggestion
SEMI
IF
LPAREN
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +RBRACK
```suggestion
IDENT(y)
RPAREN
LBRACK
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +ELSE
```suggestion
RBRACK
ELSE
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +ELSE
Wait... did I forget to implement else keyword? I don't think `py-lexer` knows this keyboard. Oops!

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +IDENT(printf)
```suggestion
RBRACK
IDENT(printf)
LPAREN
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +STR
```suggestion
RBRACK

IDENT(printf)
STR(%d)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +SEMI
```suggestion
IDENT(max)
RPAREN
SEMI
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test1.c
> +RBRACK
```suggestion
RBRACK
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +STR
```suggestion
STR(stdio.h)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +LBRACK
```suggestion
IDENT(main)
LPAREN
RPAREN
LBRACK
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +FLOAT_WORD
```suggestion
FLOAT_WORD
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +FLOAT
```suggestion
FLOAT(10.0)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +FLOAT_WORD
```suggestion
SEMI
FLOAT_WORD
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +FLOAT
```suggestion
FLOAT(4.0)
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +RETURN
```suggestion
SEMI
RETURN
```

2023-11-03 21:09 UTC, adityaxdiwakar commented on tests/test2.c
> +
```suggestion
SEMI
RBRACK
```

2023-11-03 21:25 UTC, adityaxdiwakar commented on .github/workflows/run_py-lexer.yml
> +
```suggestion
```

2023-11-03 22:03 UTC, adityaxdiwakar commented on .github/workflows/run_py-lexer.yml
> +          done
```suggestion       
          for file in tests/*
          do
            echo "Testing $file against lexer"
            if [ -f "$file" ]; then
              name="${file%.*}"
              cat $file | python3 lex.py > output
              
              diff output "expected/$name.out" > output_diff
              status = $?
              if [ status -eq 0]; then
                echo "OK."
              fi
              else
                echo "Failed. See diff below."
                cat output_diff
                exit 1
            fi
          done
```

2023-11-03 22:53 UTC, adityaxdiwakar commented
I fixed the workflow, now @CC-734 just needs to fix the tests (see previous comments) and we're good! :D

2023-11-10 16:39 UTC, CC-734 commented on tests/test1.c
> +ELSE
i changed it to indent(else) so it would pass the test but ELSE keyword would prob be nice

2023-11-10 17:29 UTC, adityaxdiwakar commented
Please leave it as ELSE. This is a bug with the lexer. It's not currently
marked as a reserved keyword.

On Fri, Nov 10, 2023, 11:40 Clare ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/test1.c
> <https://github.com/adityaxdiwakar/py-lexer/pull/2#discussion_r1389635532>
> :
>
> > +RBRACK
> +
> +ELSE
>
> i changed it to indent(else) so it would pass the test but ELSE keyword
> would prob be nice
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adityaxdiwakar/py-lexer/pull/2#discussion_r1389635532>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGK2NUQQO4ABASGKJUSJPW3YDZKGFAVCNFSM6AAAAAA644QX5SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRVGE3DSOBSGQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-11-10 18:17 UTC, adityaxdiwakar approved these changes

2023-11-10 18:18 UTC, merged